var wordsEasy = [
  'alert', 'app','api','array', 'abs', 'aaron', 'axel', 'alt', 'abbr', 'apply', 'andre', 'alec',  
  'bit', 'body', 'bind',
  'block','bug', 'break', 'bold',
  'css', 'case', 'const', 'color', 'cos', 'ctx', 'click', 'class', 'catch', 'char', 'cite', 'call',
  'data', 'dom', 'date', 'div',
  'error', 'else', 'eval', 'exp', 'em',
  'file', 'false', 'form', 'frame', 'floor', 'float', 'flex','font','for', 'find', 'felix',
  'git', 'grid', 'get',
  'html', 'host', 'href', 'http', 'https', 'head', 'hue', 'hex', 'hippo',
  'if', 'id', 'int', 'in', 'image', 'icon',
  'json', 'java', 'join', 'julia', 'jamie',
  'keyup', 'key',
  'level', 'line', 'let', 'link', 'list', 'left', 'log', 'loop', 'lang', 'laura',
  'round', 'right',
  'map', 'math', 'max', 'min', 'malte', 'matt', 'min',
  'null', 'name', 'nan', 'new', 'now',
  'parse', 'pi', 'port', 'push', 'pop', 'px', 'pow',
  'radio', 'rem', 'rgb', 'round', 'ruby',
  'scope','shift', 'set', 'sort', 'self', 'span', 'sin', 'save', 'state', 'super', 'shift', 'style', 'src', 'split', 'stack', 'sinan',
  'queue',
  'this', 'true', 'text', 'top', 'tag', 'thor',
  'type', 'title', 'tan', 'try', 'throw', 'table', 
  'url',
  'var', 'void', 'value', 'vh', 'vw',
  'www', 'while', 'width', 'web'
];

var wordsMedium = [
  'argument', 'anchor', 'acronym', 'address', 'amelia',
  'binary','bitwise','button','backend','browser','binary','bitwise','boolean','bracket','branch', 'button', 'bottom', 'border',
  'command','console', 'closure',  'charat', 'canvas',
  'default', 'decode', 'declare', 'delete', 'dynamic', 'doctype', 'define', 'datatarget',
  'event','element', 'encode', 'export', 'extends', 'enshift',
  'frontend','filter', 'finally', 'foreach',
  'github', 'global', 'getdate', 'getday', 'getyear', 'gettime',
  'header', 'heading', 'height',
  'instance', 'index', 'indexof', 'import', 'inline', 'italic', 'includes',
  'jquery', 
  'keydown', 'keyword', 'ksenia',
  'literal', 'length', 'lexical', 
  'method', 'margin', 'mutable', 'maxence', 'mongodb', 'moritz', 'marvin', 'moises',
  'nodejs', 'navigator', 'number', 'naaman',
  'object', 'onfocus', 'onclick', 'onblur', 'onload', 
  'property','pointer', 'protocol', 'pattern', 'padding', 'private', 'public', 'petter', 'pedro',
  'reduce', 'random', 'request', 'restore', 'rotate', 'return', 'runtime', 'reverse',
  'string','switch', 'submit', 'socket','syntax', 'section', 'static','search', 'status', 'section', 'setdate', 'setday', 'sethours', 'symbol', 'svenja',
  'setmonth', 'stroke', 'slice', 'splice', 'strict',
  'typeof', 'tagname', 'tofixed', 'target',
  'window',
  'vscode'
];

var wordsHard = [
  'algorithm', 'attribute', 'arithmetic', 'animation', 'absolute', 'assignment', 'anonymous', 'autofocus', 'alexander',
  'background','boxshadow', 'bootstrap', 'blockquote',
  'consolelog', 'constructor', 'checkbox', 'callback', 'character','continue', 'compiler', 'condition', 'comparator', 'comments', 'concatenate', 'compiler','camelcase',
  'document', 'drawimage', 'disabled', 'development',
  'expression', 'emmanuel',
  'flexbox', 'fontsize', 'fillrect', 'fillstyle', 'fullstack', 'fontfamily', 'federico', 'franziska',
  'getmonth', 'getseconds',
  'hostname',
  'initialize', 'immutable', 'instanceof', 'interface', 'ironhack','incrementor', 'infinite', 'ironhacker',
  'javascript', 'jennifer',
  'listener', 'listitem', 'lowercase',
  'millisecond', 'manipulate',
  'operator', 'orderlist', 'onselect', 'onsubmit', 'onunload',
  'parameter', 'position', 'parsefloat', 'parseint', 'prototype', 'primitive','paragraph', 
  'quotation',
  'relative', 'reference', 'repository',
  'selected', 'setseconds', 'substring', 'statement', 'selector', 'statistical',
  'textalign', 'textarea', 'transform', 'translate', 'typeerror', 'tranverse', 'typescript',
  'undefined', 'uppercase',
  'viewport',
];
